### PR TITLE
Web Viewer UI Updates

### PR DESCRIPTION
**Pull request by kwokcb**
# Changes
- Add in global material settings:
 - Environment sample count for FIS. Changed the default to 4 vs 16 so initial perf is not too slow.
 - Show/Hide Environment toggle.
- Add in some title coloring on folders and items.
- Add in some range values so horizontal sliders show up. 
- Add in FXAA pass but disabled this as it doesn't seem to help very much and slows down performance.

# Example
- Snapshot with new UI changes

image

- Video showing FIS sample count input value changes.
https://github.com/AcademySoftwareFoundation/MaterialX/assets/49369885/9f7c5f45-90b2-48f5-a9a2-fa8b9ce9adde

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
This looks very promising, thanks @kwokcb!

Instead of including all of these ideas in a single pull request, I'd recommend simplifying this down to one idea (e.g. the new sliders for scalar values, which provide a clear improvement over the current behavior).

Some of the other ideas presented here are interesting too, but require more discussion and refinement, e.g. the FXAA toggle, environment checkbox, and initializing folders as closed rather than opened.

**Comment by jstone-lucasfilm** [comment]
This looks very promising, thanks @kwokcb!

Instead of including all of these ideas in a single pull request, I'd recommend simplifying this down to one idea (e.g. the new sliders for scalar values, which provide a clear improvement over the current behavior).

Some of the other ideas presented here are interesting too, but require more discussion and refinement, e.g. the FXAA toggle, environment sample count, environment checkbox, and initializing folders as closed rather than opened.

**Comment by kwokcb** [comment]
I'll pull out the rest later. For now I've pulled out and complete UI attribute support (with some required fixes). in  #1623.

**Comment by kwokcb** [comment]
#1635 has additional UI changes. #1636 splits out save canvas. FXAA I will not put up a PR since it does not seem to be very good.

**Pull request closed without merging**
