### PR TITLE
Add UI limits for useSpecularWorkflow and normal in UsdPreviewSurface

### PR DESCRIPTION
**Pull request by erich666**
[UsdPreviewSurface](https://openusd.org/release/spec_usdpreviewsurface.html) allows useSpecularWorkflow to be 0 or 1. Normals should have values between -1 to 1, inclusive. This PR puts these limits into place.

### CODE REVIEW

**Comment by erich666** [comment]
Ha, no idea what those checks are about - I leave it to you all.

**Comment by erich666** [comment]
Ah, yeah, looks like some authorization thing indeed. And wow it's still crunching on 10 more tests in progress, 45 minutes later. I've added some documentation to the relevant README.md and .bat files. Happy to change any of these as you or @bernardkwok like.

**Review by jstone-lucasfilm — APPROVED** [review]
This change looks great to me, thanks @erich666!  I've reached out to the Linux Foundation for their assistance in moving the CLA approval forward.  Once that's done, we should be ready to merge this work to main.

**Comment by DerrickLFX** [comment]
Hello @erich666 if you click on the 'NOT COVERED' red button or the 'Please click here to be authorized' from the easycla bot, it will walk you through how to sign with EasyCLA. Additional info can be found here https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors
If you have any technical issues signing, the bot also provided a link to create a support ticket. 
Thank you.

**Pull request merged**
