### PR TITLE
Deterministic code generation

### PR DESCRIPTION
**Pull request by SShikhali**
These changes make code generation deterministic by changing `std::set` to `std::vector` when removing unused nodes

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
Thanks for this fix, @SShikhali, and let us know if you run into trouble with the EasyCLA process.  The Linux Foundation is usually very responsive if you submit a support ticket using the links above.

**Comment by SShikhali** [comment]
@jstone-lucasfilm should be fixed now, thanks :)

**Review by jstone-lucasfilm — COMMENTED** [review]
Thanks for putting this fix together, @SShikhali!

To make sure we don't lose any efficiency with respect to the original version, it may be better to maintain both a vector and a set, as in the following:

```
std::set<ShaderNode*> usedNodeSet;
std::vector<ShaderNode*> usedNodeVec;
```

This would allow us to efficiently maintain a vector of unique nodes with logic like the following:

```
ShaderNode* node = edge.upstream->getNode();
if (usedNodeSet.count(node) == 0)
{
    usedNodeSet.insert(node);
    usedNodeVec.push_back(node);
}
```

An at the end of the function, we could then simply replace the `resize` and `assign` calls with the following:

```
_nodeOrder = usedNodeVec;
```

**Comment by SShikhali** [comment]
@jstone-lucasfilm yes, that's better. Pushed the improved version

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @SShikhali!

I'm CC'ing @niklasharrysson for his thoughts before we merge, but I don't have any concerns on my side.

**Review by niklasharrysson — APPROVED** [review]
Looks great! Thanks for the fix @SShikhali

**Pull request merged**
