### PR TITLE
Additional improvements to MaterialX Lama nodes

### PR DESCRIPTION
**Pull request by mkuo-lucasfilm**
- Updated LamaGeneralizedSchlick implementation (changed the transmission component from a dielectric BSDF to a generalized schlick BSDF, adjusted implementation of reflectionTint)
- Updated LamaSSS and LamaTranslucent (removed LobeName and matte inputs as they are renderer-specific)
- Updated default values and help documentation of MaterialX Lama nodes to be consistent with Renderman Lama nodes.

### CODE REVIEW

**Comment by mkuo-lucasfilm** [comment]
LamaGeneralizedSchlick Render
generalized_schlick

**Review by ahostettler — COMMENTED** [review]
Thank you @mkuo-lucasfilm for updating the Lama definitions. There are still some smaller discrepancies that would be good to address, otherwise it looks good.

**Comment by mkuo-lucasfilm** [comment]
LamaGeneralizedSchlick Renders with default transmissionTint, cyan transmissionTint, and red TransmissionTint
generalized_schlick_default
generalized_schlick_cyan
generalized_schlick_red

**Review by ahostettler — COMMENTED** [review]
Thank you @mkuo-lucasfilm. There is still one small issue, otherwise it looks good.

**Review by jstone-lucasfilm — APPROVED** [review]
Great work, thanks @mkuo-lucasfilm!

**Pull request merged**
