### PR TITLE
UI Enhancements for MaterialX Graph Editor

### PR DESCRIPTION
**Pull request by kwokcb**
UI enhancement proposals:

* Add in a file menu with hotkeys
  * Move the exisitng buttons to menus, with CTRL-O, N, S for open, new and save
    

* Add in a help menu.
  * Add in all the hot-keys, and mouse short-cuts.
  * Added `L` for layout since it has none.
  * Could add a menu for graph for "hidden" functionality.
    

* Add in Viewer menu.
  * For now ad in geometry load as is possible from command line

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
This looks excellent so far, thanks @kwokcb!

One initial thought:

Since `Auto Layout` has the potential to undo an artist's choices with respect the layout of a graph, maybe we shouldn't assign this command to a hot key?

**Review by lfl-eholthouser — COMMENTED** [review]
This looks great. Thanks @bernardkwok! One minor note for the help window is that Ctrl-F is used instead of Ctrl-S to find a node by its name

**Comment by kwokcb** [comment]
Thanks for the feedback. I'll not add any new keys for now and fix the Ctrl-F. If it's okay, I'm thinking to move "Automatic Layout" under a "Graph" menu so existing hot-key items as well as new items can reside there.

**Review by jstone-lucasfilm — APPROVED** [review]
Great work, thanks @kwokcb!

**Pull request merged**
