### PR TITLE
Add a combined version define in MaterialX C++

### PR DESCRIPTION
**Pull request by ruiyang2021**
PR for https://github.com/AcademySoftwareFoundation/MaterialX/issues/1609

Also added a simple test in source/MaterialXTest/MaterialXCore/Library.cpp. Let me know if that's unnecessary

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
This looks very promising, @ruiyang2021, and I think the unit test makes a good addition (though we may want to refine exactly where it's added).

To resolve the EasyCLA error message above, feel free to follow the two links they provide in the message, and let us know how things go!

**Comment by ruiyang2021** [comment]
Gotcha, thank you! Going to sort the CLA with my manager. By the way, I'll be on holiday for 3 weeks starting from next Monday. Can come back to this one in 3 weeks if I have to leave something unfinished today

**Comment by ruiyang2021** [comment]
Hi @jstone-lucasfilm, I just passed the CLA check :)
Would it be better to add the test in Document.cpp instead? Maybe under "// Test version integers." or at the end of the file?

**Comment by jstone-lucasfilm** [comment]
Excellent, thanks @ruiyang2021!

For the location of the new test, I would actually recommend `CoreUtil.cpp`, which has tests for other MaterialXCore functions at global scope:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXTest/MaterialXCore/CoreUtil.cpp

**Review by jstone-lucasfilm — APPROVED** [review]
Great work, thanks @ruiyang2021!

**Comment by ruiyang2021** [comment]
Appreciate the help!

**Pull request merged**
