### PR TITLE
Fixes for 3-way comparison in tests_to_html.py

### PR DESCRIPTION
**Pull request by krohmerNV**
Tried to do a comparison between MDL 1.6, 1.7, and 1.8 and found two issues:
- the computed file paths are not correct when passing different `--inputdir1`, `--inputdir2`, and `--inputdir3`
- when comparing basically mdl against mdl and mdl, the file names of the diff images collide

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
@krohmerNV I like the idea of this improvement, though in my local tests it seems to break the simpler two-way comparisons between GLSL and OSL:

TwoWayComparison

**Comment by krohmerNV** [comment]
I'll investigate, thanks!

**Comment by jstone-lucasfilm** [comment]
@krohmerNV Just bumping this thread, in case you have a chance to follow up on this proposal!

**Comment by krohmerNV** [comment]
thanks @jstone-lucasfilm, I need to make time for this in the next week

**Comment by krohmerNV** [comment]
@jstone-lucasfilm updated the default parameters of the script to behave like before.
Sorry it took so long.

**Review by jstone-lucasfilm — APPROVED** [review]
Thanks for these improvements, @krohmerNV!

**Comment by jstone-lucasfilm** [comment]
Just as external validation of the PR, here are the latest GLSL/OSL render comparisons with these changes in place:

[MaterialXRenderTests_08_24_2024.pdf](https://github.com/user-attachments/files/16737715/MaterialXRenderTests_08_24_2024.pdf)

**Pull request merged**
