### PR TITLE
Fixes windows linking against shared dll for non-cmake projects

### PR DESCRIPTION
**Pull request by pmolodo**
...by ensuring that MATERIALX_BUILD_SHARED_LIBS is defined.

Fixes https://github.com/AcademySoftwareFoundation/MaterialX/issues/1066

While this `#define` is correctly generated if the project you're using is CMake based (thanks to [this issue](https://github.com/AcademySoftwareFoundation/MaterialX/issues/772) and [subsequent PR](https://github.com/AcademySoftwareFoundation/MaterialX/pull/780/files) from from @JGamache-autodesk and @bernardkwok), not all projects using MaterialX will use CMake, and the lack of the `#define MATERIALX_BUILD_SHARED_LIBS` resulted in linking errors that looked like this:

```
error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const MaterialX_v1_38_4::EMPTY_STRING" (?EMPTY_STRING@MaterialX_v1_38_4@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
```

### CODE REVIEW

**Comment by pmolodo** [comment]
Notice this is failing the EasyCLA check.  I should already be added to the CLA, as part of NVIDIA, but it looks like the email that got added was my personal email, `elrond79@gmail.com`.  Could we add / switch to my work email, `pmolodowitch@nvidia.com`? If that's a pain, I can amend the commit to use my personal email...

**Review by JGamache-autodesk — APPROVED** [review]

**Comment by pmolodo** [comment]
The EasyCLA issue may also have been because I had not associated my pmolodowitch@nvidia.com email with my github account yet!  I have done so now...

**Review by jstone-lucasfilm — APPROVED** [review]
This change looks good to me.  Thanks for the fix, @pmolodo!

**Pull request merged**
