### PR TITLE
Improvements to PyMaterialX docstrings

### PR DESCRIPTION
**Pull request by StefanHabel**
This PR tweaks the docstrings of all `PyMaterialX*` modules to be more descriptive:

| Module | Before | After |
|-|-|-|
| `PyMaterialXCore` | Module containing Python bindings for the MaterialXCore library | Core MaterialX elements and graph traversal. |
| `PyMaterialXFormat` | Module containing Python bindings for the MaterialXFormat library | Cross-platform support for file and search paths, and XML serialization. |
| `PyMaterialXGenShader` | Module containing Python bindings for the MaterialXGenShader library | Core shader generation support for MaterialX. |
| `PyMaterialXGenGlsl` | Module containing Python bindings for the MaterialXGenGlsl library | Shader generation using the OpenGL Shading Language. |
| `PyMaterialXGenMdl` | Module containing Python bindings for the MaterialXGenMdl library | Shader generation using the Material Definition Language. |
| `PyMaterialXGenMsl` | Module containing Python bindings for the MaterialXGenMsl library | Shader generation using the Metal Shading Language. |
| `PyMaterialXGenOsl` | Module containing Python bindings for the MaterialXGenOsl library | Shader generation using the Open Shading Language. |
| `PyMaterialXRender` | Module containing Python bindings for the MaterialXRender library | Core rendering support for MaterialX. |
| `PyMaterialXRenderGlsl` | Module containing Python bindings for the MaterialXRenderGlsl library | Rendering materials using the OpenGL Shading Language. |
| `PyMaterialXRenderOsl` | Module containing Python bindings for the MaterialXRenderOsl library | Rendering materials using the Open Shading Language. |
| `PyMaterialXRenderMsl` | Module containing Python bindings for the MaterialXRenderMsl library | Rendering materials using the Metal Shading Language. |

Note that the docstrings for individual classes, methods, and functions are to be added in separate PRs.

Split from #1567.

Update #342.

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
@StefanHabel I'd be interested in more details as to how `__doc__.md.h` is generated.  Is this purely a derived product, which could become a generated artifact of our build process?  Or is it a new authored document that would need to be maintained over time as the MaterialX Python libraries evolve?

**Comment by StefanHabel** [comment]
@jstone-lucasfilm  The latter:
> a new authored document that would need to be maintained over time as the MaterialX Python libraries evolve

In https://github.com/AcademySoftwareFoundation/MaterialX/pull/1567, I had originally included the docstring content in `PyModule.cpp` itself, but that made that file a bit unwieldy to work with:

```cpp
PYBIND11_MODULE(PyMaterialXCore, mod)
{
    mod.doc() = "Module containing Python bindings for the MaterialXCore library";
    mod.doc() = PYMATERIALX_DOCSTRING(R"docstring(
    Core MaterialX elements and graph traversal.

    All functions and classes that are defined in this module are available in
    the top-level `MaterialX` Python package, and are typically used via an
    `import` alias named `mx`:

    .. code:: python

        import MaterialX as mx

    Library Version
    ---------------

    .. autofunction:: getVersionIntegers
    .. autofunction:: getVersionString

    Document Element Tree
    ---------------------

    .. autofunction:: createDocument
    .. autofunction:: getConnectedOutputs
    .. autofunction:: prettyPrint

    Element Classes
    ---------------

    **Class Hierarchy**

    * `Element`
        * `TypedElement`
            * `InterfaceElement`
                * `GraphElement`
                    * `Document`
                    * `NodeGraph`
                * `Implementation`
                * `Node`
[...]
```
Original source: https://github.com/AcademySoftwareFoundation/MaterialX/pull/1567/files#diff-c07c3059ad8da7e96f14a432373a60a73b4b7cfb5708999dc9cf7ff827be3ba2


In this proposal here, the docstring contents live in separate header files named `__doc__.md.h`:
- `__doc__` for their closeness to Python docstrings
- `.md` since the docstrings use markdown format
- ending on `.h` since they are header files that define a macro

Since the filename starts with an underscore, editors like VS Code may list them at the top of the respective directory, helping to make it easy to find and make changes to the module docstring as the API evolves:

Screenshot 2024-10-01 at 09 33 32

**Comment by jstone-lucasfilm** [comment]
@StefanHabel Is there potentially an approach that would generate these documents at build time, so that we're not adding a new mandatory step for developers when they update the Python API of MaterialX?

As you might imagine, I'm concerned about adding overhead for developers contributing new features and improvements to MaterialX, where they would need to know about and update the text in these new files as well!

**Comment by StefanHabel** [comment]
@jstone-lucasfilm The proposed `__doc__.md.h` files are intended only for the docstring of the respective module itself.

Documentation of individual classes, methods, and functions that may be defined in a module would still live in the `PyModule.cpp` files and other similar implementation files themselves.

The module docstring acts as an index of the module, allowing us to group classes and module-level functions into sections of related functionality, e.g.
```md
Library Version
---------------

.. autofunction:: getVersionIntegers
.. autofunction:: getVersionString

Document Element Tree
---------------------

.. autofunction:: createDocument
.. autofunction:: getConnectedOutputs
.. autofunction:: prettyPrint
```
We can also use it for editorial style documentation such as in this example:
```md
All functions and classes that are defined in this module are available in
the top-level `MaterialX` Python package, and are typically used via an
`import` alias named `mx`:

.. code:: python

    import MaterialX as mx
```

The module docstring may also contain documentation for module-level variables, e.g.
```md
Module Constants
----------------

.. py:data:: DEFAULT_TYPE_STRING
    :type: str
    :value: "color3"

    The name of the default type that is used when no other specific type
    is given/available.

    :see: `InterfaceElement.addInput()`
    :see: `InterfaceElement.addOutput()`

.. py:data:: FILENAME_TYPE_STRING
    :type: str
    :value: "filename"

    :see: `StringResolver.resolve()`

.. py:data:: GEOMNAME_TYPE_STRING
    :type: str
    :value: "geomname"

    :see: `StringResolver.resolve()`

[...]
```

The presence of this more comprehensive and (hopefully) helpful documentation comes at a cost of having to keep it up to date with changes in the codebase, which is a concern indeed.

For example, when adding a new function, we'd add its definition including a docstring in `PyModule.cpp`, and would then also update the corresponding sections in `__doc__.md.h`, to include the new function in the relevant listings.

**Comment by StefanHabel** [comment]
I've uploaded the generated docs to the live demo version here, if you'd like to have a look at the rendered output:

https://stefanhabel.github.io/generated/PyMaterialXCore.html

**Comment by StefanHabel** [comment]
`PyMaterialXCore` is arguably the heaviest example.

In `PyMaterialXRender`, for example, this proposed editorial approach to delivering developer documentation allows us to offer a curated list of sections that are intended to be more helpful than a mere alphabetical listing:

https://stefanhabel.github.io/generated/PyMaterialXRender.html

**Comment by StefanHabel** [comment]
(All this will look much better once docstrings for classes, methods, and functions have been added.)

**Comment by StefanHabel** [comment]
Intended result with docstrings for functions added:

Screenshot 2023-10-21 at 14 28 03

**Comment by jstone-lucasfilm** [comment]
@StefanHabel Could there somehow be a way to extract these details from the associated Doxygen comments in our C++ classes, so that we don't need to manually keep the Python documentation in sync?

Selecting just one typical example, here's the class hierarchy that's automatically generated from the Doxygen comments for the `Element` class in MaterialXCore:

https://materialx.org/docs/api/class_element.html

And here's the corresponding text that you've proposed for the `__doc__.md.h` file for the `Element` class in PyMaterialXCore:

```
* `Element`
    * `TypedElement`
        * `InterfaceElement`
            * `GraphElement`
                * `Document`
                * `NodeGraph`
            * `Implementation`
            * `Node`
            * `NodeDef`
            * `Variant`
        * `ValueElement`
            * `PortElement`
                * `Input`
                * `Output`
            * `GeomProp`
            * `Property`
            * `PropertyAssign`
            * `Token`
        * `AttributeDef`
        * `GeomPropDef`
        * `Member`
        * `TargetDef`
    * `GeomElement`
        * `GeomInfo`
        * `MaterialAssign`
        * `PropertySetAssign`
        * `Visibility`
    * `Backdrop`
    * `Collection`
    * `CommentElement`
    * `GenericElement`
    * `Look`
    * `LookGroup`
    * `NewlineElement`
    * `PropertySet`
    * `TypeDef`
    * `Unit`
    * `UnitDef`
    * `UnitTypeDef`
    * `VariantSet`
    * `VariantAssign`
```

Since these class hierarchies are nearly identical, could there be a way to keep these two sets of derived data automatically in sync, perhaps extracting the required text from the same Doxygen comments in the C++ codebase?

I should note that I honestly don't know the answer to these questions, and this is an area where I clearly need to learn more!

**Comment by StefanHabel** [comment]
Thanks @jstone-lucasfilm!

I'm sharing your concerns!

Another downside of the approach proposed here is that the docstring that is visible in interactive Python sessions would contain all of those markup instructions, which is not ideal.

Here's an example based on this branch:
```python
Python 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 16.0.0 (clang-1600.0.26.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyMaterialXCore
>>> print(PyMaterialXCore.__doc__)
Core MaterialX elements and graph traversal.

All functions and classes that are defined in this module are available in
the top-level `MaterialX` Python package, and are typically used via an
`import` alias named `mx`:

.. code:: python

    import MaterialX as mx

Library Version
---------------

.. autofunction:: getVersionIntegers
.. autofunction:: getVersionString

Document Element Tree
---------------------

.. autofunction:: createDocument
.. autofunction:: getConnectedOutputs
.. autofunction:: prettyPrint

Element Classes
---------------

**Class Hierarchy**

* `Element`
    * `TypedElement`
        * `InterfaceElement`
            * `GraphElement`
                * `Document`
                * `NodeGraph`
            * `Implementation`
            * `Node`
            * `NodeDef`
            * `Variant`
        * `ValueElement`
            * `PortElement`
                * `Input`
                * `Output`
            * `GeomProp`
            * `Property`
            * `PropertyAssign`
            * `Token`
        * `AttributeDef`
        * `GeomPropDef`
        * `Member`
        * `TargetDef`
    * `GeomElement`
        * `GeomInfo`
        * `MaterialAssign`
        * `PropertySetAssign`
        * `Visibility`
    * `Backdrop`
    * `Collection`
    * `CommentElement`
    * `GenericElement`
    * `Look`
    * `LookGroup`
    * `NewlineElement`
    * `PropertySet`
    * `TypeDef`
    * `Unit`
    * `UnitDef`
    * `UnitTypeDef`
    * `VariantSet`
    * `VariantAssign`
* `Edge`
* `StringResolver`

**Alphabetical Index**

.. autosummary::
    :toctree: elements

    AttributeDef
    Backdrop
    Collection
    CommentElement
    Document
    Edge
    Element
    GenericElement
    GeomElement
    GeomInfo
    GeomProp
    GeomPropDef
    GraphElement
    Implementation
    Input
    InterfaceElement
    Look
    LookGroup
    MaterialAssign
    Member
    NewlineElement
    Node
    NodeDef
    NodeGraph
    Output
    PortElement
    Property
    PropertyAssign
    PropertySet
    PropertySetAssign
    StringResolver
    TargetDef
    Token
    TypeDef
    TypedElement
    Unit
    UnitDef
    UnitTypeDef
    ValueElement
    Variant
    VariantAssign
    VariantSet
    Visibility

Value Classes
-------------

**Class Hierarchy**

* `Value`
    * `TypedValued` -- The class template for typed subclasses of `Value`
        * `TypedValue_boolean`
        * `TypedValue_booleanarray`
        * `TypedValue_color3`
        * `TypedValue_color4`
        * `TypedValue_float`
        * `TypedValue_floatarray`
        * `TypedValue_integer`
        * `TypedValue_integerarray`
        * `TypedValue_matrix33`
        * `TypedValue_matrix44`
        * `TypedValue_string`
        * `TypedValue_stringarray`
        * `TypedValue_vector2`
        * `TypedValue_vector3`
        * `TypedValue_vector4`
* `MatrixBase`
    * `Matrix33`
    * `Matrix44`
* `VectorBase`
    * `Vector2`
    * `Vector3`
    * `Vector4`
* `Color3`
* `Color4`

**Alphabetical Index**

.. autosummary::
    :toctree: value-classes

    Color3
    Color4
    Matrix33
    Matrix44
    MatrixBase
    TypedValue_boolean
    TypedValue_booleanarray
    TypedValue_color3
    TypedValue_color4
    TypedValue_float
    TypedValue_floatarray
    TypedValue_integer
    TypedValue_integerarray
    TypedValue_matrix33
    TypedValue_matrix44
    TypedValue_string
    TypedValue_stringarray
    TypedValue_vector2
    TypedValue_vector3
    TypedValue_vector4
    Value
    Vector2
    Vector3
    Vector4
    VectorBase

Material Node Utilities
-----------------------

.. autofunction:: getGeometryBindings
.. autofunction:: getShaderNodes

Iterator Classes
----------------

.. autosummary::
    :toctree: iterators

    GraphIterator
    InheritanceIterator
    TreeIterator

Predicate Classes
-----------------

.. autosummary::
    :toctree: predicates

    ElementPredicate
    NodePredicate

Unit Converter Classes
----------------------

**Class Hierarchy**

* `UnitConverter`
    * `LinearUnitConverter`
* `UnitConverterRegistry`

**Alphabetical Index**

.. autosummary::
    :toctree: unit-converters

    LinearUnitConverter
    UnitConverter
    UnitConverterRegistry

Exception Classes
-----------------

**Class Hierarchy**

* `Exception`
    * `ExceptionFoundCycle`
    * `ExceptionOrphanedElement`
    * `PyMaterialXFormat.ExceptionFileMissing`
    * `PyMaterialXFormat.ExceptionParseError`
    * `PyMaterialXRender.ExceptionRenderError`

**Alphabetical Index**

.. autosummary::
    :toctree: exceptions

    Exception
    ExceptionFoundCycle
    ExceptionOrphanedElement

Name/Path Utilities
-------------------

.. autofunction:: createNamePath
.. autofunction:: createValidName
.. autofunction:: incrementName
.. autofunction:: isValidName
.. autofunction:: parentNamePath
.. autofunction:: splitNamePath

String Utilities
----------------

.. autofunction:: joinStrings
.. autofunction:: replaceSubstrings
.. autofunction:: splitString
.. autofunction:: stringEndsWith
.. autofunction:: stringStartsWith
.. autofunction:: geomStringsMatch
.. autofunction:: targetStringsMatch

Module Constants
----------------

.. py:data:: DEFAULT_TYPE_STRING
    :type: str
    :value: "color3"

    The name of the default type that is used when no other specific type
    is given/available.

    :see: `InterfaceElement.addInput()`
    :see: `InterfaceElement.addOutput()`

.. py:data:: FILENAME_TYPE_STRING
    :type: str
    :value: "filename"

    :see: `StringResolver.resolve()`

.. py:data:: GEOMNAME_TYPE_STRING
    :type: str
    :value: "geomname"

    :see: `StringResolver.resolve()`

.. py:data:: STRING_TYPE_STRING
    :type: str
    :value: "string"

.. py:data:: BSDF_TYPE_STRING
    :type: str
    :value: "BSDF"

.. py:data:: EDF_TYPE_STRING
    :type: str
    :value: "EDF"

.. py:data:: VDF_TYPE_STRING
    :type: str
    :value: "VDF"

.. py:data:: SURFACE_SHADER_TYPE_STRING
    :type: str
    :value: "surfaceshader"

    The node type name used for surface shader nodes.

    :see: `getShaderNodes()`

.. py:data:: DISPLACEMENT_SHADER_TYPE_STRING
    :type: str
    :value: "displacementshader"

    The node type name used for displacement shader nodes.

    :see: `getShaderNodes()`

.. py:data:: VOLUME_SHADER_TYPE_STRING
    :type: str
    :value: "volumeshader"

    The node type name used for volume shader nodes.

    :see: `getShaderNodes()`

.. py:data:: LIGHT_SHADER_TYPE_STRING
    :type: str
    :value: "lightshader"

    The node type name used for light shader nodes.

    :see: `getShaderNodes()`

.. py:data:: MATERIAL_TYPE_STRING
    :type: str
    :value: "material"

.. py:data:: SURFACE_MATERIAL_NODE_STRING
    :type: str
    :value: "surfacematerial"

.. py:data:: VOLUME_MATERIAL_NODE_STRING
    :type: str
    :value: "volumematerial"

.. py:data:: MULTI_OUTPUT_TYPE_STRING
    :type: str
    :value: "multioutput"

.. py:data:: NONE_TYPE_STRING
    :type: str
    :value: "none"

.. py:data:: VALUE_STRING_TRUE
    :type: str
    :value: "true"

.. py:data:: VALUE_STRING_FALSE
    :type: str
    :value: "false"

.. py:data:: NAME_PREFIX_SEPARATOR
    :type: str
    :value: ":"

.. py:data:: NAME_PATH_SEPARATOR
    :type: str
    :value: "/"

.. py:data:: ARRAY_VALID_SEPARATORS
    :type: str
    :value: ", "

.. py:data:: ARRAY_PREFERRED_SEPARATOR
    :type: str
    :value: ", "

.. py:data:: GEOM_PATH_SEPARATOR
    :type: str
    :value: "/"

.. py:data:: UNIVERSAL_GEOM_NAME
    :type: str
    :value: GEOM_PATH_SEPARATOR

    :see: `GEOM_PATH_SEPARATOR`
    :see: `getGeometryBindings()`

.. py:data:: UDIM_TOKEN
    :type: str
    :value: "<UDIM>"

.. py:data:: UV_TILE_TOKEN
    :type: str
    :value: "<UVTILE>"

.. py:data:: UDIM_SET_PROPERTY
    :type: str
    :value: "udimset"
```
Further noting that Python already provides an auto-generated class hierarchy in the form of a tree in its generated `help()` text:
```python
>>> help(PyMaterialXCore)
[...]
CLASSES
    builtins.Exception(builtins.BaseException)
        Exception
        ExceptionFoundCycle
        ExceptionOrphanedElement
    pybind11_builtins.pybind11_object(builtins.object)
        Edge
        Element
            Backdrop
            Collection
            CommentElement
            GenericElement
            GeomElement
                GeomInfo
                MaterialAssign
                PropertySetAssign
                Visibility
            Look
            LookGroup
            NewlineElement
            PropertySet
            TypeDef
            TypedElement
                AttributeDef
                GeomPropDef
                InterfaceElement
                    GraphElement
                        Document
                        NodeGraph
                    Implementation
                    Node
                    NodeDef
                    Variant
                Member
                TargetDef
                ValueElement
                    GeomProp
                    PortElement
                        Input
                        Output
                    Property
                    PropertyAssign
                    Token
            Unit
            UnitDef
            UnitTypeDef
            VariantAssign
            VariantSet
        ElementPredicate
        GraphIterator
        InheritanceIterator
        MatrixBase
            Matrix33
            Matrix44
        NodePredicate
        StringResolver
        TreeIterator
        UnitConverter
            LinearUnitConverter
        UnitConverterRegistry
        Value
            TypedValue_boolean
            TypedValue_booleanarray
            TypedValue_color3
            TypedValue_color4
            TypedValue_float
            TypedValue_floatarray
            TypedValue_integer
            TypedValue_integerarray
            TypedValue_matrix33
            TypedValue_matrix44
            TypedValue_string
            TypedValue_stringarray
            TypedValue_vector2
            TypedValue_vector3
            TypedValue_vector4
        VectorBase
            Color3
            Color4
            Vector2
            Vector3
            Vector4
[...]
```
With that in mind, I'd propose:
- Removing these separate `__doc__.md.h` files again
- Keeping the new single-line descriptions of the MaterialX Python API modules (as I think they're informative than only stating that the modules are bindings to underlying code, e.g.
  ```diff
  -    mod.doc() = "Module containing Python bindings for the MaterialXCore library";
  +    mod.doc() = "Core MaterialX elements and graph traversal.";
  ```
- Exploring ways of automatically generating additional contents in markdown pages of the main modules only at build time (when the Python API documentation is generated)
  - We would be keeping this information completely separate from the information that is provided in docstrings within the API itself
  - We could do this under a separate ticket and PRs later, after the core functionality of generating Python API documentation has been established

**Comment by jstone-lucasfilm** [comment]
@StefanHabel Thanks for that excellent breakdown, and I think the path forward that you propose is the right one!

**Comment by StefanHabel** [comment]
OK cool!

I've rebased the branch of this PR on top of `main`, and have added another commit to remove the separate `__doc__.md.h` again, leaving only the single change of the module's docstring: https://github.com/AcademySoftwareFoundation/MaterialX/pull/2039/commits/064a0758bca3014427a655925f38461bdc906715

As this is now the only change in this PR, perhaps we could combine a couple or all of these PRs into one, to reduce the overhead (and so as not to artificially inflate my contribution count 😅)?

- https://github.com/AcademySoftwareFoundation/MaterialX/pull/2039
- https://github.com/AcademySoftwareFoundation/MaterialX/pull/2040
- https://github.com/AcademySoftwareFoundation/MaterialX/pull/2041
- https://github.com/AcademySoftwareFoundation/MaterialX/pull/2042

As we've been using this PR to discuss these changes in general, I'm inclined to add the single-line docstring changes for the other modules to the branch of this PR as well, and to close the other 3 PRs as cancelled.

**Comment by jstone-lucasfilm** [comment]
Sounds good!  I agree that's the most accurate way to document the evolution of this project, and feel free to combine all of those single-line changes into this PR.

**Comment by StefanHabel** [comment]
Done:
- Other module docstrings updated in https://github.com/AcademySoftwareFoundation/MaterialX/pull/2039/commits/b57a1413bac969f8de232401cf01cf72e22be1ca
- Description of PR updated
- Title of PR updated: _Tweaking docstrings of PyMaterialX* modules._

The name of the branch in this fork remains as `StefanHabel:#342-PyMaterialXCore-docstring`. Hope that's OK

**Comment by StefanHabel** [comment]
I've updated the live demo at https://stefanhabel.github.io to reflect these changes.

**Comment by StefanHabel** [comment]
While here, we could take this opportunity to update the `README.md` file in the `PyMaterialX` directory accordingly, as it does not currently list all of these modules yet:

> # Python Support
>
> A Python package is created from the following modules. The OSL and GLSL modules can
be conditionally built.
>
> - [PyMaterialXCore](PyMaterialXCore): Python module for MaterialX core
> - [PyMaterialXFormat](PyMaterialXFormat): Python module for XML serialization support
> - [PyMaterialXGenShader](PyMaterialXGenShader) : Python module for core shader generation
> - [PyMaterialXGenOsl](PyMaterialXGenOsl) : Python module for OSL shader generation
> - [PyMaterialXGenGlsl](PyMaterialXGenGlsl) : Python module for GLSL shader generation

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/PyMaterialX/README.md

Then again, similar updates in other `README.md` files could perhaps be better grouped in a separate PR specifically for `README.md` files.

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @StefanHabel!

**Pull request merged**
