### PR TITLE
Adding LamaGeneralizedSchlick and LamaIridescence Nodes

### PR DESCRIPTION
**Pull request by mkuo-lucasfilm**
1. Added a LamaGeneralizedSchlick node to MaterialX (Renderman definition: https://rmanwiki.pixar.com/display/REN26/LamaGeneralizedSchlick)

2. Added a LamaIridescence node to MaterialX (Renderman definition: https://rmanwiki.pixar.com/display/REN26/LamaIridescence)

### CODE REVIEW

**Comment by mkuo-lucasfilm** [comment]
generalizedschlick
iridescence

LamaGeneralizedSchlick and LamaIridescence renders

**Comment by mkuo-lucasfilm** [comment]
LamaGeneralizedSchlick Render
generalizedschlick

**Comment by mkuo-lucasfilm** [comment]
LamaIridescence Render
iridescence

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @mkuo-lucasfilm!

**Pull request merged**
