### PR TITLE
Improve MDL thin-film support

### PR DESCRIPTION
**Pull request by krohmerNV**
- push down the thin film parameters to the nodes that can use them, i.e., dielectric, conductor and generalized schlick
- removed additional inputs, that transport thin film parameters, from the public material interface by making them non-editable
- make sure thin_film will not result in undefined behavior when passing zeros as parameters (0 thickness disables thin_film but 0 ior is invalid)

- Vertical Layering, push base deeper than one level, needs review, contains TODOs for mix, add, and multiply (If not 100% sure this is correct, we can drop that commit and postpone.

### CODE REVIEW

**Comment by pablode** [comment]
Hello! I'm seeing a regression when I use these changes with my MaterialX/MDL-based renderer:

| Before | After|
|--- |--- |
| latest_master_1 | new_pr_1 |

I've prepared a glTF+mtlx version of this asset in hope that it can be reproduced with the MDL SDK DXR example:
[maneki_gltf.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/11006837/maneki_gltf.zip)

**Comment by krohmerNV** [comment]
I can reproduce it. And it showed another problem as well:
When reading the the normal texture, the output is color and connecting that to a float3 in MDL requires and explicit type construction (because color could be spectral). 
But I'm a bit surprised about the missing gold here. I'll investigate and keep you posted.
 
image

**Comment by krohmerNV** [comment]
Looking into the regression and it revealed an MDL bug which will be fixed with MDL 1.8. Meanwhile, I added a workaround to detect the problematic case and handle it correctly.

**Comment by kwokcb** [comment]
If we want the vec3 version of USDUVTexture how about we bring it up in the MTLX/USD channel and see what folks have to say.
IMO, it's an implementation variant and not a spec change but would need to discuss as it still produces 2 implementation signature variants for USD to consume.

**Comment by krohmerNV** [comment]
@jstone-lucasfilm and @kwokcb is there something outstanding for this PR? I believe the type of the usd texture return rgb is a different topic discussed in https://github.com/AcademySoftwareFoundation/MaterialX/issues/1038

**Comment by jstone-lucasfilm** [comment]
@krohmerNV As long as the original regression noted by @pablode has been addressed, I'm not aware of any outstanding issues, and I'll plan to take a closer look at these changes soon.

**Review by jstone-lucasfilm — APPROVED** [review]
Thanks for this improvement, @krohmerNV, and this looks good to me!

**Pull request merged**
