### PR TITLE
Initial translation from `standard_surface` to `open_pbr_surface`

### PR DESCRIPTION
**Pull request by mkuo-lucasfilm**
1. Authored an initial pass at the translation graph between standard surface and OpenPBR

2. Added units to standard surface thin film thickness documentation

### CODE REVIEW

**Comment by mkuo-lucasfilm** [comment]
Copper translation example from standard surface to OpenPBR
standard_surface_copper
standard_surface_copper_open_pbr

**Comment by mkuo-lucasfilm** [comment]
Brass tiled example from standard surface (top) to OpenPBR (bottom)
standard_surface_brass
standard_surface_brass_open_pbr

**Comment by mkuo-lucasfilm** [comment]
Car paint translation example from standard surface (top) to OpenPBR (bottom) - could be improved
standard_surface_carpaint
standard_surface_carpaint_open_pbr

**Review by jstone-lucasfilm — APPROVED** [review]
This looks great to me, thanks @mkuo-lucasfilm, and I'd say that we should merge this to main, while still encouraging additional ideas and proposed improvements from the community.

**Pull request merged**
