### PR TITLE
Fix Graph Editor unintentional camera orbit in render view

### PR DESCRIPTION
**Pull request by LeaRe**
This fixes the logic that detects whether the cursor is in the render view. Previously, there were three known issues that are fixed with this change:
- The camera would orbit when grabbing the scrollbar located next to the render view.
- The camera would orbit when clicking a menu option in the menu dropdown overlapping the render view.
- The previous logic to detect the cursor in the render view did not consider that the render view moves up when scrolling. As a result, the camera would still orbit when clicking parts of the Node Property Editor that were previously occupied by the render view.

### CODE REVIEW

**Comment by LeaRe** [comment]
This change fixes issue #1984 and another similar issue I noticed during this work (see comment in issue).

**Comment by jstone-lucasfilm** [comment]
This looks really promising, @LeaRe, and I'm CC'ing @lfl-eholthouser for her expertise with this code.

**Comment by lfl-eholthouser** [comment]
This looks great, @LeaRe! Thanks

**Review by jstone-lucasfilm — APPROVED** [review]
Great work on this project, thanks @LeaRe!

**Pull request merged**
