### PR TITLE
Simplify OSL test setup

### PR DESCRIPTION
**Pull request by ld-kerley**
Use the OSL cmake exports to configure the variables needed to enable OSL testing.

Also remove the need for specifying the standard OSL include path, an `oslc` install will already know where these are.

### CODE REVIEW

**Comment by ld-kerley** [comment]
This is ready to go - pending someone who works on Windows validating that this still allows OSL to be used with windows.

**Comment by jstone-lucasfilm** [comment]
This proposal looks very promising to me, and I should have a chance to test it soon with Windows OSL (which uses a less standardized build approach and folder structure).

**Comment by jstone-lucasfilm** [comment]
@ld-kerley In my local test, I get an error message from CMake before I have a chance to select any build options, so this seems to occur even if the user doesn't choose to build with OSL support:

```
CMake Warning at CMakeLists.txt:185 (find_package):
  By not providing "FindOSL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OSL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OSL" with any of
  the following names:

    OSLConfig.cmake
    osl-config.cmake

  Add the installation prefix of "OSL" to CMAKE_PREFIX_PATH or set "OSL_DIR"
  to a directory containing one of the above files.  If "OSL" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by ld-kerley** [comment]
@jstone-lucasfilm - was this an error message in CMake, or just a warning and things continued?  I would expect things to have just continued, albeit with an annoyingly loud warning.

I just pushed a PR where I'm quietening the warning, and also guarding the check to only when we need it (testing OSL).

**Comment by jstone-lucasfilm** [comment]
@ld-kerley I believe you're correct that this was just a warning, though CMake makes it look as if the warning is fatal through the use of red text.  Let me try the latest build and see how things are looking now.

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @ld-kerley!

**Pull request merged**
