### PR TITLE
Add nodegraph implementations for color and vector smoothstep

### PR DESCRIPTION
**Pull request by ld-kerley**
Issue #1978 reports an issue with repeated code for the `smoothstep` node.  

This PR will resolve that issue (and also add a unit test that demonstrates the issue) by converting all the `smoothstep` nodes to nodegraph implementations.

This PR also simplifies the nodegraphs for `smoothstep` to allow follow the same pattern.
```
<separateX>  ->  <ND_smoothstep_float>  ->  <combineX>
```

### CODE REVIEW

**Review by jstone-lucasfilm — COMMENTED** [review]
This looks like a good improvement to me, @ld-kerley!

In order to minimize duplication, would it make sense to implement the `color3` and `color4` variants in terms of the `vector3` and `vector4` versions, with `convert` nodes used for the type conversions?

**Comment by ld-kerley** [comment]
I started out with that, and then opted for the version I pushed because I thought it would be easier to maintain because of the parity across all the different type implementations, and I also started to worry about the quality of the generated shader code with additional conversions.

I just briefly surveyed the existing nodegraph implementations and most (perhaps all) of the existing nodegraph implementations in `stdlib_ng.mtlx` that support the typical array of types all currently provide their own implementation for each type.  

And finally now I'm writing this, I'm wondering if the type conversion approach might complicate any overhaul of colorspace things in MaterialX in the future - having distinct implementations feels like it might be beneficial.

**Comment by jstone-lucasfilm** [comment]
Those sound like good arguments to me, @ld-kerley, and perhaps we can consider this type of implementation sharing as an option for the future, where it would be applied globally if at all.

**Comment by jstone-lucasfilm** [comment]
Since there's a parallel discussion about the correct behavior of `smoothstep` on the MaterialX channel of the ASWF Slack, it seems worthwhile to ask whether we should adopt the recommendations of that thread as part of this change, or whether these changes should be considered and committed independently:

https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1724060123942189

What are your thoughts?

**Comment by ld-kerley** [comment]
I was just reading Larrys commit to OSL - https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/commit/67e886e9e24880f8618c07feeea8102926ad76ec

Which is the opposite of what we're currently doing for GLSL/MSL.

I think I would vote for a separate PR - which I can put up soon.  The change is easy, but we might want to debate/socialize a little that the change is coming with the wider community.

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @ld-kerley!

**Pull request merged**
