### PR TITLE
Add OPENIMAGEIO_UTIL_LIBRARY to OpenImageIO

### PR DESCRIPTION
**Pull request by mikaelsundell**

### CODE REVIEW

**Comment by lgritz** [comment]
Aside: Is there a reason to have a FindOpenImageIO, can you not rely on the exported configs that OIIO has had for a few years now?

**Comment by mikaelsundell** [comment]
Good question, this is a quick fix to make sure the ParamValue+List symbols are resolved during build. Should I give it a try and change to the OpenImageIO*.cmake configs?

**Comment by lgritz** [comment]
I think it depends on what is the oldest version of OIIO you want to support.

**Comment by jstone-lucasfilm** [comment]
@lgritz @mikaelsundell Perhaps we can take this in two stages, first addressing the missing functionality in our existing FindOpenImageIO, and then proposing an update that would allow us to remove it entirely?  Before we restrict the range of OpenImageIO versions that we support, I'd ideally like to check with the MaterialX TSC and make sure we're not stranding any existing users.

**Comment by mikaelsundell** [comment]
@lgritz @jstone-lucasfilm Agree, I can prepare another PR using the OIIO configs for consideration in the meantime. Tried it yesterday within my build system and it's not much work.

**Review by jstone-lucasfilm — APPROVED** [review]
This looks good to me, thanks @mikaelsundell!

**Pull request merged**
